#!/usr/bin/env python
from relay_sdk import Interface, Dynamic as D
import boto3

region = 'ap-southeast-1'
relay = Interface()
to_start = []

instances = filter(lambda i: i['State']['Name'] != 'running', relay.get(D.instances))
for instance in instances:
    to_start.append(instance['InstanceId'])

ec2 = boto3.client('ec2', region_name=region)

result = ec2.start_instances(InstanceIds=instances)

print(result)
    
print('\nFound {} instances to start:'.format(len(to_start)))
print(*[instance_id for instance_id in to_start], sep = "\n") 

relay.outputs.set('instanceIDs', to_start)
